<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_HaltNC_TestDouble" Id="{f9b66d85-7bb4-402b-9f8b-2a0adea12002}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HaltNC_TestDouble IMPLEMENTS  I_Halt
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <CFC>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="CFCImplementationObject">
              <o n="Items" t="CFCItemList">
                <l2 n="InnerList" />
              </o>
              <n n="ParameterInitializationMethodGenerator" />
              <o n="RoutingPathTable" t="CFCRoutingPathTable">
                <d2 n="InnerDictionary" />
              </o>
              <v n="AutoSizeCanvas">true</v>
              <v n="CanvasWidth">2</v>
              <v n="CanvasHeight">2</v>
              <n n="EditorConfiguration" />
              <v n="AreElementsSpaceOptimized">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
            <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
            <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
            <Type n="Int32">System.Int32</Type>
          </TypeList>
        </XmlArchive>
      </CFC>
    </Implementation>
    <Property Name="Aborted" Id="{93737e43-fd27-4bc9-ba9b-223268f682f3}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Aborted : BOOL
]]></Declaration>
      <Get Name="Get" Id="{fef0ec11-61d3-4e40-a4b0-f1ca0db49a20}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Get>
    </Property>
    <Property Name="Active" Id="{2b37f2d8-d99f-4670-9e2e-6850dbfbedbf}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Active : BOOL
]]></Declaration>
      <Get Name="Get" Id="{8e8336dc-0a95-41af-9c36-72bf717dcc13}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Get>
    </Property>
    <Property Name="Busy" Id="{034fa069-6878-4483-aee8-f3158caaf3b6}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Busy : BOOL
]]></Declaration>
      <Get Name="Get" Id="{b063851c-4493-4d17-ae35-c9062adea97f}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Get>
    </Property>
    <Property Name="CommandHalt" Id="{086e355b-6176-40fc-aa49-523c080ad882}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY CommandHalt : BOOL
]]></Declaration>
      <Set Name="Set" Id="{5538a0dc-0e1c-45bd-acb0-31a7a9925af1}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Set>
    </Property>
    <Property Name="Done" Id="{a4f4af90-5ae1-4477-b229-6a6b6705b3dd}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Done : BOOL
]]></Declaration>
      <Get Name="Get" Id="{b1cf0137-23e5-4693-b43b-e15d2c9344c1}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Get>
    </Property>
    <Property Name="Error" Id="{cc116eda-d8d1-4a1d-82e6-92ac9919db6f}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Error : BOOL
]]></Declaration>
      <Get Name="Get" Id="{5fcda727-bdc7-41fc-9341-c44594191003}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Get>
    </Property>
    <Property Name="ErrorID" Id="{d686636c-b18c-4f6b-855d-6b987cd35849}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY ErrorID : UDINT
]]></Declaration>
      <Get Name="Get" Id="{70e690d0-ec33-418c-8670-d56a804c91a0}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Get>
    </Property>
    <Method Name="Halt" Id="{6b0a130f-519e-48ff-97cd-c37fb031ebbf}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD Halt
VAR_INPUT
    Deceleration	: LREAL := 0;
    Jerk	: LREAL := 0;
    BufferMode	: MC_BufferMode := .MC_BufferMode.MC_Aborting;
END_VAR
]]></Declaration>
      <Implementation>
        <CFC>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCImplementationObject">
                <o n="Items" t="CFCItemList">
                  <l2 n="InnerList" />
                </o>
                <n n="ParameterInitializationMethodGenerator" />
                <o n="RoutingPathTable" t="CFCRoutingPathTable">
                  <d2 n="InnerDictionary" />
                </o>
                <v n="AutoSizeCanvas">true</v>
                <v n="CanvasWidth">0</v>
                <v n="CanvasHeight">0</v>
                <n n="EditorConfiguration" />
                <v n="AreElementsSpaceOptimized">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
              <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
              <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
              <Type n="Int32">System.Int32</Type>
            </TypeList>
          </XmlArchive>
        </CFC>
      </Implementation>
      <ObjectProperties>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="CFCProperty">
              <v n="UseExplicitExecutionOrder">false</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
          </TypeList>
        </XmlArchive>
      </ObjectProperties>
    </Method>
    <Property Name="Message" Id="{9dd1b35c-115d-4a93-bec5-c49881409ad8}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Message : T_MAXSTRING
]]></Declaration>
      <Get Name="Get" Id="{4afe19f6-0305-4dc4-be85-e22907dd5c3a}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Get>
    </Property>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="CFCProperty">
            <v n="UseExplicitExecutionOrder">false</v>
          </o>
        </Data>
        <TypeList>
          <Type n="Boolean">System.Boolean</Type>
          <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
  </POU>
</TcPlcObject>