<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_MoveAbsoluteNC_TestDouble" Id="{a1299b88-c1cc-47e6-86d2-69eec76abb7c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_MoveAbsoluteNC_TestDouble IMPLEMENTS I_MoveAbsolute
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <CFC>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="CFCImplementationObject">
              <o n="Items" t="CFCItemList">
                <l2 n="InnerList" />
              </o>
              <n n="ParameterInitializationMethodGenerator" />
              <o n="RoutingPathTable" t="CFCRoutingPathTable">
                <d2 n="InnerDictionary" />
              </o>
              <v n="AutoSizeCanvas">true</v>
              <v n="CanvasWidth">2</v>
              <v n="CanvasHeight">2</v>
              <n n="EditorConfiguration" />
              <v n="AreElementsSpaceOptimized">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
            <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
            <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
            <Type n="Int32">System.Int32</Type>
          </TypeList>
        </XmlArchive>
      </CFC>
    </Implementation>
    <Property Name="Aborted" Id="{d4e3cd51-5fee-4db6-8208-a2bc7e9fdd7a}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Aborted : BOOL
]]></Declaration>
      <Get Name="Get" Id="{26c0c97b-2d18-473c-9b75-fe721f82f49f}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Get>
    </Property>
    <Property Name="Active" Id="{09738852-52fb-4077-a45f-6ebfef7b4a86}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Active : BOOL
]]></Declaration>
      <Get Name="Get" Id="{5e775f9a-a8f6-4a42-974f-288cf114ff26}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Get>
    </Property>
    <Property Name="Busy" Id="{39175115-a127-49c4-80ac-dffa8f64dda2}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Busy : BOOL
]]></Declaration>
      <Get Name="Get" Id="{5ac749c2-ac2c-41cb-a308-ca6e922fd588}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Get>
    </Property>
    <Property Name="CommandMoveAbsolute" Id="{9eb83c04-aa48-4f9f-a6a7-3768920423d4}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY CommandMoveAbsolute : BOOL
]]></Declaration>
      <Set Name="Set" Id="{d7d59388-2f0d-423e-82ff-f43ef092b308}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Set>
    </Property>
    <Property Name="Done" Id="{6c26a443-e660-4fcf-999f-11731e43cb8f}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Done : BOOL
]]></Declaration>
      <Get Name="Get" Id="{e1981ecc-2030-40ce-9a7c-d8a1d2e391e3}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Get>
    </Property>
    <Property Name="Error" Id="{bd80d191-eec2-449f-96a3-3506f67108a1}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Error : BOOL
]]></Declaration>
      <Get Name="Get" Id="{0ea3b5eb-6486-46c5-902c-adf45a253412}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Get>
    </Property>
    <Property Name="ErrorID" Id="{c366e1bd-70a4-48f4-838b-8982d7690ce1}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY ErrorID : UDINT
]]></Declaration>
      <Get Name="Get" Id="{0ef34ba1-602b-4eac-8648-615a36e3bda6}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Get>
    </Property>
    <Property Name="Message" Id="{682bc89a-ba45-4a9c-bd43-aa24d1d42359}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Message : T_MAXSTRING
]]></Declaration>
      <Get Name="Get" Id="{ad285937-0e0d-43a8-965c-8779c9795f7b}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Get>
    </Property>
    <Method Name="MoveAbsolute" Id="{9d7d7069-91ef-47be-85d8-0bfdfbbff977}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD MoveAbsolute
VAR_INPUT
    Position	: LREAL;
    Velocity	: LREAL;
    Acceleration	: LREAL := 0;
    Deceleration	: LREAL := 0;
    Jerk	: LREAL := 0;
    BufferMode	: MC_BufferMode := .MC_BufferMode.MC_Aborting;
END_VAR
]]></Declaration>
      <Implementation>
        <CFC>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCImplementationObject">
                <o n="Items" t="CFCItemList">
                  <l2 n="InnerList" />
                </o>
                <n n="ParameterInitializationMethodGenerator" />
                <o n="RoutingPathTable" t="CFCRoutingPathTable">
                  <d2 n="InnerDictionary" />
                </o>
                <v n="AutoSizeCanvas">true</v>
                <v n="CanvasWidth">0</v>
                <v n="CanvasHeight">0</v>
                <n n="EditorConfiguration" />
                <v n="AreElementsSpaceOptimized">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
              <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
              <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
              <Type n="Int32">System.Int32</Type>
            </TypeList>
          </XmlArchive>
        </CFC>
      </Implementation>
      <ObjectProperties>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="CFCProperty">
              <v n="UseExplicitExecutionOrder">false</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
          </TypeList>
        </XmlArchive>
      </ObjectProperties>
    </Method>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="CFCProperty">
            <v n="UseExplicitExecutionOrder">false</v>
          </o>
        </Data>
        <TypeList>
          <Type n="Boolean">System.Boolean</Type>
          <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
  </POU>
</TcPlcObject>