<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_WriteParameterNC_TestDouble" Id="{585873b6-7f78-428d-a151-a1ef70c92da6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_WriteParameterNC_TestDouble IMPLEMENTS  I_WriteParameter
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <CFC>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="CFCImplementationObject">
              <o n="Items" t="CFCItemList">
                <l2 n="InnerList" />
              </o>
              <n n="ParameterInitializationMethodGenerator" />
              <o n="RoutingPathTable" t="CFCRoutingPathTable">
                <d2 n="InnerDictionary" />
              </o>
              <v n="AutoSizeCanvas">true</v>
              <v n="CanvasWidth">2</v>
              <v n="CanvasHeight">2</v>
              <n n="EditorConfiguration" />
              <v n="AreElementsSpaceOptimized">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
            <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
            <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
            <Type n="Int32">System.Int32</Type>
          </TypeList>
        </XmlArchive>
      </CFC>
    </Implementation>
    <Property Name="Aborted" Id="{7396920b-2600-424f-9c6c-770311b58147}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Aborted : BOOL
]]></Declaration>
      <Get Name="Get" Id="{c8e136ef-2c49-45f2-835f-402f6de965d7}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Get>
    </Property>
    <Property Name="Active" Id="{a386a0b0-2594-44cc-8652-b40c3432108f}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Active : BOOL
]]></Declaration>
      <Get Name="Get" Id="{2a23fc67-b513-4551-9c11-33d28ec4831e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Get>
    </Property>
    <Property Name="Busy" Id="{ee2addf4-3000-45bf-93ee-5c6d9199c1f3}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Busy : BOOL
]]></Declaration>
      <Get Name="Get" Id="{d7030bbf-37ba-4166-8a3b-c535d58f2b7f}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Get>
    </Property>
    <Property Name="Done" Id="{285e3e5d-9d50-4f87-ac74-f6629d45e656}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Done : BOOL
]]></Declaration>
      <Get Name="Get" Id="{4f5689bb-076c-40a7-bd20-ace516750671}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Get>
    </Property>
    <Property Name="Error" Id="{062ba1c5-be7a-4fe9-8b23-dcf7b5a13d3a}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Error : BOOL
]]></Declaration>
      <Get Name="Get" Id="{24f0f280-919f-4cac-bd35-881b4630d462}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Get>
    </Property>
    <Property Name="ErrorID" Id="{874f763c-3159-412b-99e6-d6549eeb89d8}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY ErrorID : UDINT
]]></Declaration>
      <Get Name="Get" Id="{89605898-8cb2-4fb2-b49e-b1d0641a8bee}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Get>
    </Property>
    <Property Name="Message" Id="{98221eac-3ece-43a4-8c71-2195803f72fb}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Message : T_MAXSTRING
]]></Declaration>
      <Get Name="Get" Id="{63537d90-ad5e-4a72-89fb-9e94f99a34f5}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <CFC>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="CFCImplementationObject">
                  <o n="Items" t="CFCItemList">
                    <l2 n="InnerList" />
                  </o>
                  <n n="ParameterInitializationMethodGenerator" />
                  <o n="RoutingPathTable" t="CFCRoutingPathTable">
                    <d2 n="InnerDictionary" />
                  </o>
                  <v n="AutoSizeCanvas">true</v>
                  <v n="CanvasWidth">0</v>
                  <v n="CanvasHeight">0</v>
                  <n n="EditorConfiguration" />
                  <v n="AreElementsSpaceOptimized">false</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
                <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
                <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
                <Type n="Int32">System.Int32</Type>
              </TypeList>
            </XmlArchive>
          </CFC>
        </Implementation>
        <ObjectProperties>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCProperty">
                <v n="UseExplicitExecutionOrder">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
            </TypeList>
          </XmlArchive>
        </ObjectProperties>
      </Get>
    </Property>
    <Method Name="WriteParameter" Id="{7d0bfa80-d3f9-4353-95de-f3619b083423}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD WriteParameter
VAR_INPUT
    Execute	: BOOL;
    ParameterNumber	: MC_AxisParameter;
    ParameterValue	: LREAL;
END_VAR
]]></Declaration>
      <Implementation>
        <CFC>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCImplementationObject">
                <o n="Items" t="CFCItemList">
                  <l2 n="InnerList" />
                </o>
                <n n="ParameterInitializationMethodGenerator" />
                <o n="RoutingPathTable" t="CFCRoutingPathTable">
                  <d2 n="InnerDictionary" />
                </o>
                <v n="AutoSizeCanvas">true</v>
                <v n="CanvasWidth">0</v>
                <v n="CanvasHeight">0</v>
                <n n="EditorConfiguration" />
                <v n="AreElementsSpaceOptimized">false</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
              <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
              <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
              <Type n="Int32">System.Int32</Type>
            </TypeList>
          </XmlArchive>
        </CFC>
      </Implementation>
      <ObjectProperties>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="CFCProperty">
              <v n="UseExplicitExecutionOrder">false</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
          </TypeList>
        </XmlArchive>
      </ObjectProperties>
    </Method>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="CFCProperty">
            <v n="UseExplicitExecutionOrder">false</v>
          </o>
        </Data>
        <TypeList>
          <Type n="Boolean">System.Boolean</Type>
          <Type n="CFCProperty">{97c1f2ea-5995-48b9-abd5-a3ab983c5def}</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
  </POU>
</TcPlcObject>