<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_StateMachine_TestDouble" Id="{bd4c0fda-2c0f-4d99-bff0-ed190100a01c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_StateMachine_TestDouble IMPLEMENTS I_StateMachine
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Idling" Id="{4d1775a0-7b36-4458-b6bc-000998f7c70b}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Idling : BOOL
]]></Declaration>
      <Get Name="Get" Id="{0ae0842e-3354-4ebf-a230-b2374daccdd0}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="MoveState" Id="{5b8ab468-efd2-474c-930c-53db7f21c503}">
      <Declaration><![CDATA[PROPERTY MoveState : E_MOVESTATE
]]></Declaration>
      <Get Name="Get" Id="{d8032f69-63db-4d74-bbc2-c680fd7b80fa}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="Reset" Id="{383ec148-d063-4e0d-97e4-d0532d5bda33}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD Reset
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="StateMachine" Id="{53a2f700-2d7e-4499-830f-475a67ac2b82}">
      <Declaration><![CDATA[METHOD StateMachine
VAR_INPUT
	Error : BOOL;
	InterlockEvent : BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="WatchDogStatus" Id="{e6fb2611-cf62-410c-b73d-4c60b0873c32}">
      <Declaration><![CDATA[PROPERTY WatchDogStatus : BOOL
]]></Declaration>
      <Get Name="Get" Id="{6302b0ad-2cc0-4385-83f3-ee776beb4493}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="WatchDogTimeOut" Id="{18a85cf8-05cc-4f4c-b8a1-59a6774c4d9d}">
      <Declaration><![CDATA[PROPERTY WatchDogTimeOut : BOOL
]]></Declaration>
      <Get Name="Get" Id="{0ada9824-d6e4-439b-a047-2c42f8f82b99}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>