<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_DS402Common" Id="{aad06df2-4217-4751-9c86-ffbd9fc2d324}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_DS402Common IMPLEMENTS I_DS402Common
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Aborted" Id="{07ea345d-8dca-46bc-9c5c-6542ce170857}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY Aborted : BOOL
]]></Declaration>
      <Get Name="Get" Id="{4ca8a777-e1df-4551-b7c2-c69415d6716e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Busy" Id="{7bc2389e-952f-4770-b75d-0b39950b9d84}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY Busy : BOOL
]]></Declaration>
      <Get Name="Get" Id="{f5c30a94-7811-4d6b-b148-b74237330908}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Done" Id="{764ffdf8-5aca-46ae-86d0-1c6021257d11}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY Done : BOOL
]]></Declaration>
      <Get Name="Get" Id="{0254fe8d-8b66-47b5-8387-319c08c76d15}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Error" Id="{484e0c3b-c86f-4a7f-ba10-e5ac0af18c30}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Error : BOOL
]]></Declaration>
      <Get Name="Get" Id="{5a8064fc-2816-4796-a44c-0633f6bf9182}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="ErrorID" Id="{437cb84c-1119-4ece-bf26-d3a9d738aeab}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY ErrorID : UDINT
]]></Declaration>
      <Get Name="Get" Id="{c9c4bd0f-8763-4430-abc3-d54299e223b9}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="Home" Id="{675f9ecc-13ae-47a3-b771-2ac300675623}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD  Home
VAR_INPUT
    Enable	: BOOL;
    HomeSpeedFast	: LREAL;
    HomeSpeedSlow	: LREAL;
    HomeOffset	: LREAL;
    HomePosition	: LREAL := 0;
    UserAbort	: BOOL;
    HomeMethod	: E_EpicsHomeCmd;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="HomeBusy" Id="{8b4f7e06-72b0-43ac-bb5a-151a3994ffe1}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY HomeBusy : BOOL
]]></Declaration>
      <Get Name="Get" Id="{830a1b0b-c27b-42f2-86e3-7ff892cb2d19}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="HomeDone" Id="{29d4a963-ddb6-47db-a859-e825248d0e0c}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY HomeDone : BOOL
]]></Declaration>
      <Get Name="Get" Id="{fc972ac0-86bc-4283-b8da-3636408bb685}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="HomeMode" Id="{d25b95b5-57ca-404e-be22-81078a950b29}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY HomeMode : E_EpicsHomeCmd
]]></Declaration>
      <Get Name="Get" Id="{89dfc96a-7ef4-4616-ba1d-e7489298732a}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{89cc1899-620f-4777-8c8b-ff6d0ba27afd}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Property Name="HomeOffset" Id="{f01fd84d-967d-47ae-9931-e4eff49f3acc}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY HomeOffset : LREAL
]]></Declaration>
      <Get Name="Get" Id="{773f8c55-2ec5-44a8-81c5-eb614812e535}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{b795dbbd-3605-4bd8-90b1-74bc12a202a2}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Property Name="HomePosition" Id="{a91f65e2-6906-4968-b6fe-79c1bafa9c0c}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY HomePosition : LREAL
]]></Declaration>
      <Get Name="Get" Id="{6e20bc2d-1d4f-4a2d-8c5d-a31d68a477eb}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{17192189-e677-4744-9bc4-9d3b973bb84f}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Property Name="Message" Id="{4f46d136-c452-4527-b339-0b3d129c6b5f}">
      <Declaration><![CDATA[{warning 'Add property implementation'}
PROPERTY Message : T_MAXSTRING
]]></Declaration>
      <Get Name="Get" Id="{79505d8a-35ba-4bf4-9334-4d29159bc1db}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Mode" Id="{d8c56e29-2ee2-4d45-944e-0504bd644565}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY Mode : E_EpicsHomeCmd
]]></Declaration>
      <Get Name="Get" Id="{75347523-9e12-4fe4-8de4-46060548af8f}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{0662b160-6407-4b59-a212-bed0ff01e4aa}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Property Name="Offset" Id="{f09da615-b0a7-4f05-a491-3051ac263d75}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY Offset : LREAL
]]></Declaration>
      <Get Name="Get" Id="{31592049-27bf-46f4-946c-017d37df4acd}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{a70ba3b2-3427-4711-a984-6009ca3b61f8}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Method Name="OperationMode" Id="{4c3d8f00-eabb-46e9-b1a5-50a91b585cbd}">
      <Declaration><![CDATA[{warning 'Add method implementation '}
METHOD OperationMode
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Position" Id="{f4bac636-356f-4dd5-b306-881715d5a410}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY Position : LREAL
]]></Declaration>
      <Get Name="Get" Id="{1d2bec56-b61a-4df6-a1b4-6cd6d6f754dd}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{2599968e-5335-4717-b9cd-c382a2f96701}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Property Name="RefVeloSearch" Id="{99bde7b5-c90c-4d56-a888-b29f726e9a8d}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY RefVeloSearch : LREAL
]]></Declaration>
      <Get Name="Get" Id="{027d97dd-0420-4609-82a9-b64714e474d2}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="RefVeloSync" Id="{b82d9fb2-9c6f-49d5-a2aa-6d5de21096c5}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY RefVeloSync : LREAL
]]></Declaration>
      <Get Name="Get" Id="{79fbbd76-0d41-43f3-9c0d-c27db2db4f54}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>